my_app_mail:
    resource: "@MyAppMailBundle/Resources/config/routing.yml"
    prefix:   /ab

tunisia_mall:
    resource: "@TunisiaMallBundle/Resources/config/routing.yml"
    prefix:   /

first:
    resource: "@FirstBundle/Resources/config/routing.yml"
    prefix:   /abc

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /