tunisia_mall:
    resource: "@TunisiaMallBundle/Resources/config/routing.yml"
    prefix:   /

first:
    resource: "@FirstBundle/Resources/config/routing.yml"
    prefix:   /abc

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

