# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_RESPONSABLE: ROLE_RESPONSABLE


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username



    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login


            logout:       true
            anonymous:    true

    access_control:
            - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/adminindex, roles: ROLE_ADMIN }
            - { path: ^/shop/, roles: ROLE_RESPONSABLE }





