tunisia_mall_reservationPlaceParking:
    resource: "@TunisiaMallBundle/Resources/config/routing/reservationpp.yml"
    prefix:   /reservationPlaceParkingX
tunisia_mall_homepage:
    path:     /
    defaults: { _controller: TunisiaMallBundle:Default:index }

tunisia_mall_signup:
    path:     /signup
    defaults: { _controller: TunisiaMallBundle:Default:signup }

tunisia_mall_contact:
    path:     /contact
    defaults: { _controller: TunisiaMallBundle:Default:Contact }

tunisia_mall_AboutPage:
    path:     /about
    defaults: { _controller: TunisiaMallBundle:Default:about }

tunisia_mall_ajout_evenement:
    path:     /ajoutevenement
    defaults: { _controller: TunisiaMallBundle:Evenement:ajoutevenement }

tunisia_mall_list_evenement:
    path:     /adminevenement
    defaults: { _controller: TunisiaMallBundle:Evenement:listevenement }

tunisia_mall_modifier_evenement:
    path:     /modifierevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:modifierevenement }

tunisia_mall_supprimer_evenement:
    path:     /supprimerevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:supprimerevenement }

tunisia_mall_admin_homepage:
    path:     /adminindex
    defaults: { _controller: TunisiaMallBundle:Default:adminindex }

tunisia_mall_admin_evenement:
    path:     /adminevenement
    defaults: { _controller: TunisiaMallBundle:Default:adminevenement }

tunisia_mall_client_evenement:
    path:     /clientevenement
    defaults: { _controller: TunisiaMallBundle:Default:clientevenement }

offreAdmin:
    path:     /offreAdmin
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:affichAll }

ToAjout:
    path:     /ToAjout
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:ToAjout }

ajoutOffreAdmin:
    path:     /ajoutOffreAdmin
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:ajout }

modifOffreAdmin:
    path:     /modifOffreAdmin/{idOffre}
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:modifier }

suppOffreAdmin:
    path:     /suppOffreAdmin/{idOffre}
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:supprimer }

demandeAdmin:
    path:     /demandeAdmin
    defaults: { _controller: TunisiaMallBundle:DemandeEmploi:affichAlladmin }

tunisia_mall_admin_publicite:
    path:     /adminpub
    defaults: { _controller: TunisiaMallBundle:Publicite:listpub }

tunisia_mall_admin_ajout_publicite:
    path:     /ajoutpub
    defaults: { _controller: TunisiaMallBundle:Publicite:ajoutpub }

tunisia_mall_modifier_publicite:
    path:     /modifierpublicite/{id}
    defaults: { _controller: TunisiaMallBundle:Publicite:modifierpub }

tunisia_mall_supprimer_publicite:
    path:     /supprimerpublicite/{id}
    defaults: { _controller: TunisiaMallBundle:Publicite:supprimerpublicte }

tunisia_mall_contactinternaute:
    path:     /contacti
    defaults: { _controller: TunisiaMallBundle:Default:iContact }
tunisia_mall_GBoutiqueCA:
    path:     /GestionBoutique
    defaults: { _controller: TunisiaMallBundle:Boutique:ajoutboutique }
tunisia_mall_list_boutique:
    path:     /listboutique
    defaults: { _controller: TunisiaMallBundle:Boutique:afficherboutiques }
tunisia_mall_supprimer_boutique:
    path:     /supprimerboutique/{id}
    defaults: { _controller: TunisiaMallBundle:Boutique:supprimerboutique }
tunisia_mall_modifier_boutique:
    path:     /modifierboutique/{id}
    defaults: { _controller: TunisiaMallBundle:Boutique:modifierBoutique }

tunisia_mall_addProduit:
    path:     /addproduit
    defaults: { _controller: TunisiaMallBundle:Produit:AjoutProduit }


tunisia_mall_chat:
    path:     /chat
    defaults: { _controller: TunisiaMallBundle:Produit:chat }

tunisia_mall_chatshop:
    path:     /shop
    defaults: { _controller: TunisiaMallBundle:Produit:shop }



tunisia_mall_promoproduittotal:
    path:     /shop/listproduit/promotionproduittotal
    defaults: { _controller: TunisiaMallBundle:promotion:promoproduittotal }




tunisia_mall_modifierproduit:
    path:     /modifierProduit/{id_produit}
    defaults: { _controller: TunisiaMallBundle:Produit:modifierProduit }





tunisia_mall_modifierPromotion:
    path:     /modifierPromotion/{idPromotion}
    defaults: { _controller: TunisiaMallBundle:promotion:modifierPromotion }

tunisia_mall_shopowner_evenement:
    path:     /shopownerevenement2
    defaults: { _controller: TunisiaMallBundle:Default:shopownerevenement }

tunisia_mall_shopowner_ajout_evenement:
    path:     /shopownerajoutevenement
    defaults: { _controller: TunisiaMallBundle:EvenementShopowner:ajouterevenement }

tunisia_mall_shopowner_list_evenement:
    path:     /shopownerevenement1
    defaults: { _controller: TunisiaMallBundle:EvenementShopowner:listevenement }

tunisia_mall_shopowner_modifier_evenement:
    path:     /shopownermodifierevenement/{id}
    defaults: { _controller: TunisiaMallBundle:EvenementShopowner:modifierevenement }

tunisia_mall_shopowner_supprimer_evenement:
    path:     /shopownersupprimerevenement/{id}
    defaults: { _controller: TunisiaMallBundle:EvenementShopowner:supprimerevenement }

tunisia_mall_exemple_evenement:
    path:     /exempleevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:exempleevenement }




tunisia_mall_AjouterReview:
    path:     /detailleprod/AjouterReview/{id_dis}
    defaults: { _controller: TunisiaMallBundle:Review:AjouterReview }


tunisia_mall_exemplprody:
    path:     /detailleprod/{id}
    defaults: { _controller: TunisiaMallBundle:Produit:exemplprody }
tunisia_mall_clientaffichagewatch:
    path:     /watch
    defaults: { _controller: TunisiaMallBundle:Produit:affichagewatch }


tunisia_mall_clientaffichageclothes:
    path:     /clothes
    defaults: { _controller: TunisiaMallBundle:Produit:affichageclothes }

tunisia_mall_listProduit:
    path:     /listproduit
    defaults: { _controller: TunisiaMallBundle:Produit:listProduit }

tunisia_mall_chat:
    path:     /chat
    defaults: { _controller: TunisiaMallBundle:Produit:chat }



tunisia_mall_promoproduitx:
    path:     /shop/listproduit/promotionproduitx/{id_produit}
    defaults: { _controller: TunisiaMallBundle:promotion:AjoutPromotion }




tunisia_mall_suppproduit:
    path:     /shop/shop/listproduit/{id_produit}
    defaults: { _controller: TunisiaMallBundle:Produit:Suppprod }


tunisia_mall_supppromotion:
    path:     /shop/shop/promotionproduittotal/{id_promotion}
    defaults: { _controller: TunisiaMallBundle:promotion:Supppromotion }




tunisia_mall_client_produitaffichage:
    path:     /clientprodaffichage
    defaults: { _controller: TunisiaMallBundle:Default:clientproduit }
tunisia_mall_list_reclamation:
    path:     /listreclamation
    defaults: { _controller: TunisiaMallBundle:Reclamation:afficherreclamations}
tunisia_mall_supprimer_reclamation:
    path:     /supprimerreclamation/{id}
    defaults: { _controller: TunisiaMallBundle:Reclamation:supprimerReclamation }
tunisia_mall_Repondre_Reclamation:
    path:     /repondrereclamation/{id}
    defaults: { _controller: TunisiaMallBundle:Reclamation:RepondreReclamation }

my_app_mail_accuse:
    path:     /success
    defaults: { _controller: TunisiaMallBundle:Reclamation:success }
tunisia_mall_list_reclamation_shop:
    path:     /listreclamationshop
    defaults: { _controller: TunisiaMallBundle:Reclamation:afficherreclamationsshop}


tunisia_mall_shopowner_demande_ajout_publicite:
    path:     /demandeajoutpub
    defaults: { _controller: TunisiaMallBundle:Publicite:demandeajoutpub }

tunisia_mall_admin_liste_demande_publicite:
    path:     /adminlistedemandepub
    defaults: { _controller: TunisiaMallBundle:Publicite:listdemandepub }

tunisia_mall_admin_accept_ajout_publicite:
    path:     /acceptajoutpub/{id}
    defaults: { _controller: TunisiaMallBundle:Publicite:acceptajoutpub }

tunisia_mall_admin_supprimer_publicite:
    path:     /refuserdemandepublicite/{id}
    defaults: { _controller: TunisiaMallBundle:Publicite:refuserpublicte }

tunisia_mall_admin_liste_responsable_boutique:
    path:     /listeresponsableboutique
    defaults: { _controller: TunisiaMallBundle:User:listeresponsableboutique }

tunisia_mall_ajout_responsable_boutique:
    path:     /ajoutresponsableboutique
    defaults: { _controller: TunisiaMallBundle:User:ajoutresponsableboutique }

tunisia_mall_compose_sms:
    path:     /composersms
    defaults: { _controller: TunisiaMallBundle:Default:composersms }

tunisia_mall_send_sms:
    path:     /sendsms
    defaults: { _controller: TunisiaMallBundle:Default:sendsms }

tunisia_mall_modifier_responsable_boutique:
    path:     /modifierresponsableBoutique/{id}
    defaults: { _controller: TunisiaMallBundle:User:modifierresponsable }

tunisia_mall_admin_supprimer_responsable_boutique:
    path:     /supprimerresponsableboutique/{id}
    defaults: { _controller: TunisiaMallBundle:User:supprimerresponsable }


offreclient:
    path:     /offreclient
    defaults: { _controller: TunisiaMallBundle:DemandeEmploi:afficherOffre }

ajouterDemande:
    path:     /ajouterDemande/{idOffre}
    defaults: { _controller: TunisiaMallBundle:DemandeEmploi:ajouterDemande }

demandelist:
    path:     /demandelist
    defaults: { _controller: TunisiaMallBundle:DemandeEmploi:affichAllclient }

modifierdemande:
    path:     /modifierdemande/{idDemande}
    defaults: { _controller: TunisiaMallBundle:DemandeEmploi:modifier }

supprimerdemande:
    path:     /supprimerdemande/{idDemande}
    defaults: { _controller: TunisiaMallBundle:DemandeEmploi:supprimer }


affichShopowner:
    path:     /affichShopowner
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:affichShopowner }

ajoutShopowner:
    path:     /ajoutShopowner
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:ajoutShopowner }

supprimerShop:
    path:     /supprimerShop/{idOffre}
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:supprimerShop }

modifierShop:
    path:     /modifierShop/{idOffre}
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:modifierShop }

affichShopownerDemande:
    path:     /affichShopownerDemande
    defaults: { _controller: TunisiaMallBundle:DemandeEmploi:affichShopownerDemande }

clientoffredetails:
    path:     /clientoffredetails/{idOffre}
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:affichdetailClient }

statproduit:
    path:     /statproduit
    defaults: { _controller: TunisiaMallBundle:Graphe:chartHistogramme }

tunisiamall_count:
    path:     /count
    defaults: { _controller: TunisiaMallBundle:Publicite:count }

ajaxtest:
    path:     /call
    defaults: { _controller: TunisiaMallBundle:Default:updateData  }
statpie:
    path:     /statpie
    defaults: { _controller: TunisiaMallBundle:Graphe:chartPie }
