tunisia_mall_homepage:
    path:     /
    defaults: { _controller: TunisiaMallBundle:Default:index }

tunisia_mall_signup:
    path:     /signup
    defaults: { _controller: TunisiaMallBundle:Default:signup }

tunisia_mall_contact:
    path:     /contact
    defaults: { _controller: TunisiaMallBundle:Default:Contact }

tunisia_mall_AboutPage:
    path:     /about
    defaults: { _controller: TunisiaMallBundle:Default:about }

tunisia_mall_ajout_evenement:
    path:     /ajoutevenement
    defaults: { _controller: TunisiaMallBundle:Evenement:ajoutevenement }

tunisia_mall_list_evenement:
    path:     /adminevenement
    defaults: { _controller: TunisiaMallBundle:Evenement:listevenement }

tunisia_mall_modifier_evenement:
    path:     /modifierevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:modifierevenement }

tunisia_mall_supprimer_evenement:
    path:     /supprimerevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:supprimerevenement }

tunisia_mall_admin_homepage:
    path:     /adminindex
    defaults: { _controller: TunisiaMallBundle:Default:adminindex }

tunisia_mall_admin_evenement:
    path:     /adminevenement
    defaults: { _controller: TunisiaMallBundle:Default:adminevenement }

tunisia_mall_client_evenement:
    path:     /clientevenement
    defaults: { _controller: TunisiaMallBundle:Default:clientevenement }


tunisia_mall_contactinternaute:
    path:     /contacti
    defaults: { _controller: TunisiaMallBundle:Default:iContact }
tunisia_mall_GBoutiqueCA:
    path:     /GestionBoutique
    defaults: { _controller: TunisiaMallBundle:Boutique:ajoutboutique }
tunisia_mall_list_boutique:
        path:     /listboutique
        defaults: { _controller: TunisiaMallBundle:Boutique:afficherboutiques }
tunisia_mall_supprimer_boutique:
    path:     /supprimerboutique/{id}
    defaults: { _controller: TunisiaMallBundle:Boutique:supprimerboutique }
tunisia_mall_modifier_boutique:
    path:     /modifierboutique/{id}
    defaults: { _controller: TunisiaMallBundle:Boutique:modifierBoutique }
