tunisia_mall_homepage:
    path:     /
    defaults: { _controller: TunisiaMallBundle:Default:index }

tunisia_mall_signup:
    path:     /signup
    defaults: { _controller: TunisiaMallBundle:Default:signup }

tunisia_mall_contact:
    path:     /contact
    defaults: { _controller: TunisiaMallBundle:Default:Contact }

tunisia_mall_AboutPage:
    path:     /about
    defaults: { _controller: TunisiaMallBundle:Default:about }

tunisia_mall_ajout_evenement:
    path:     /ajoutevenement
    defaults: { _controller: TunisiaMallBundle:Evenement:ajoutevenement }

tunisia_mall_list_evenement:
    path:     /adminevenement
    defaults: { _controller: TunisiaMallBundle:Evenement:listevenement }

tunisia_mall_modifier_evenement:
    path:     /modifierevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:modifierevenement }

tunisia_mall_supprimer_evenement:
    path:     /supprimerevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:supprimerevenement }

tunisia_mall_admin_homepage:
    path:     /adminindex
    defaults: { _controller: TunisiaMallBundle:Default:adminindex }

tunisia_mall_admin_evenement:
    path:     /adminevenement
    defaults: { _controller: TunisiaMallBundle:Default:adminevenement }

tunisia_mall_client_evenement:
    path:     /clientevenement
    defaults: { _controller: TunisiaMallBundle:Default:clientevenement }

tunisia_mall_admin_publicite:
    path:     /adminpub
    defaults: { _controller: TunisiaMallBundle:Publicite:listpub }

tunisia_mall_admin_ajout_publicite:
    path:     /ajoutpub
    defaults: { _controller: TunisiaMallBundle:Publicite:ajoutpub }

tunisia_mall_modifier_publicite:
    path:     /modifierpublicite/{id}
    defaults: { _controller: TunisiaMallBundle:Publicite:modifierpub }

tunisia_mall_supprimer_publicite:
    path:     /supprimerpublicite/{id}
    defaults: { _controller: TunisiaMallBundle:Publicite:supprimerpublicte }
