tunisia_mall_homepage:
    path:     /
    defaults: { _controller: TunisiaMallBundle:Default:index }
tunisia_mall_signup:
    path:     /signup
    defaults: { _controller: TunisiaMallBundle::signup }
tunisia_mall_contact:
    path:     /contact
    defaults: { _controller: TunisiaMallBundle:Default:Contact }
tunisia_mall_contactinternaute:
    path:     /contacti
    defaults: { _controller: TunisiaMallBundle:Default:iContact }