tunisia_mall_homepage:
    path:     /
    defaults: { _controller: TunisiaMallBundle:Default:index }

tunisia_mall_signup:
    path:     /signup
    defaults: { _controller: TunisiaMallBundle:Default:signup }

tunisia_mall_contact:
    path:     /contact
    defaults: { _controller: TunisiaMallBundle:Default:Contact }

tunisia_mall_AboutPage:
    path:     /about
    defaults: { _controller: TunisiaMallBundle:Default:about }

tunisia_mall_ajout_evenement:
    path:     /ajoutevenement
    defaults: { _controller: TunisiaMallBundle:Evenement:ajoutevenement }

tunisia_mall_list_evenement:
    path:     /adminevenement
    defaults: { _controller: TunisiaMallBundle:Evenement:listevenement }

tunisia_mall_modifier_evenement:
    path:     /modifierevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:modifierevenement }

tunisia_mall_supprimer_evenement:
    path:     /supprimerevenement/{id}
    defaults: { _controller: TunisiaMallBundle:Evenement:supprimerevenement }

tunisia_mall_admin_homepage:
    path:     /adminindex
    defaults: { _controller: TunisiaMallBundle:Default:adminindex }

tunisia_mall_admin_evenement:
    path:     /adminevenement
    defaults: { _controller: TunisiaMallBundle:Default:adminevenement }

tunisia_mall_client_evenement:
    path:     /clientevenement
    defaults: { _controller: TunisiaMallBundle:Default:clientevenement }

offreAdmin:
    path:     /offreAdmin
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:affichAll }

ToAjout:
    path:     /ToAjout
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:ToAjout }

ajoutOffreAdmin:
    path:     /ajoutOffreAdmin
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:ajout }

modifOffreAdmin:
    path:     /modifOffreAdmin/{idOffre}
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:modifier }

suppOffreAdmin:
    path:     /suppOffreAdmin/{idOffre}
    defaults: { _controller: TunisiaMallBundle:OffreEmploi:supprimer }

demandeAdmin:
    path:     /demandeAdmin
    defaults: { _controller: TunisiaMallBundle:DemandeEmploi:afficherAll }
